Features branch
rida-elbahtouri/rida-aye-youtube pull request #5
Opened 2020-04-29 14:44 UTC by rida-elbahtouri

2020-04-29 18:47 UTC, lekegitrepo commented
#### Hi @rida-elbahtouri and @rida-elbahtouri :clap: :clap:
#### Good job so far. There are requirements you need to consider before this project can be approved.

**_1. Use a single pull request for the project review._**

**_2. There should be at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))_**

**_3. It displays the avatar of the user who uploaded the video ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_avatar_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))_**

**_4. The title and numbers of view on the sidebar recommended videos should be text not image._**

**_5. Try to add a left margin to the page._**

**_if you have any doubts or questions contact me on slack._**

### _Reviewed by Temitayo Adeleke._

2020-04-29 18:48 UTC, lekegitrepo requested changes
#### Status: Request changes

2020-04-30 18:35 UTC, rammazzoti2000 requested changes
# CHANGES REQUIRED :raised_hands: 
## Hey @rida-elbahtouri and @Alaska01 :wave:
You have done a splendid job with the changes! :tada:  Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
#
Please make these changes and submit another review request.
# [REQUIRED ] - see the highlighted sections :pray: 
 - [x] The Pull Request should have a description. Pleas add description with a summary of the changes done in the project
 - [x] The readme file should have a live link that points to the actual website. My go-to resource for making live links is [Raw Githack](https://raw.githack.com/). Please check it out, it's free and easy to use :+1: 
 - [x] I should be able to play the video
- [x] The channel image is broken (bad extension) - use .JPG instead if .jpg
#
### That's it, please complete the changes require in order to have this project approved.

2020-04-30 18:35 UTC, rammazzoti2000 commented on index.html
> +        <iframe id="youtube-video"
When I try to play the video it doesn't allow me to, this is most likely oh the wrong embedded link,
try to use this one instead:
`<iframe width="1366" height="632" src="https://www.youtube.com/embed/tgbNymZ7vqY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> `

2020-04-30 18:35 UTC, rammazzoti2000 commented on index.html
> -        <img src="image/channel-icon.jpg" alt="channel-icon" class="subscribe-channel-button cusor"/> <p id="odin">The Odin Project</p>
The image of the channel is not displaying, this is because it has the wrong extension, please change it to .JPG as it is in your image folder

2020-04-30 20:22 UTC, merged

2020-05-01 09:24 UTC, trekab commented
# Changes Required!
Hi @rida-elbahtouri and @Alaska01. We are almost there! Let's work on the following few changes;

* Reduce the size of the sidebar so that it appears smaller than the main video section.
* Position the main video section buttons (subscribe, share, number of views) more appropriately to look more like the site being cloned.

__Kindly work on the above changes and submit a new code review request__

2020-05-02 02:14 UTC, uryelah commented
Hello **Aye Aye & Rida Elbahtouri**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, congrats in working on your first Microverse project 🌟**

I see you made some progress from the past reviews but there are still some issues to fix. Rest assured that when you get used to the general requirements for this module the next projects code reviews will be way easier💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Please add, re-add if it was there and you removed, a Pull request message. [Remember to keep your repo professional.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
Your message should follow the model below:
![pr_message](https://user-images.githubusercontent.com/16193212/80852550-ea2d9a80-8bff-11ea-9fb3-7be82ed31237.gif)

Here's how your current PR message looks like:
![Screenshot_2020-05-01 Features branch by rida-elbahtouri · Pull Request #5 · rida-elbahtouri rida-aye-youtube](https://user-images.githubusercontent.com/16193212/80852564-fca7d400-8bff-11ea-8a6c-a54a147fda88.png)


----

- [ ] Make sure to follow CSS best practices. You should not use id selectors to style, change them to class selectors. [This article explains a bit why that is.](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4)

----

- Please fix the positioning of the main video background so it's white behind it. Check the current issue with your clone:
![Screenshot_2020-05-01 Youtube(2)](https://user-images.githubusercontent.com/16193212/80852571-05000f00-8c00-11ea-8752-e86da8f3fa93.png)

- [ ] Style your buttons so they don't have a grey background or borders. Compare how your navbar and the original one look and fix it to be closer.
- [ ] Pay attention to the vertical size of the search input and button, they should be aligned like the original.
**Clone:**
![Screenshot_2020-05-01 Youtube(1)](https://user-images.githubusercontent.com/16193212/80852572-0598a580-8c00-11ea-983c-44528b0e74fd.png)
**Correct navbar:**
![Screenshot_2020-05-01 YouTube](https://user-images.githubusercontent.com/16193212/80852573-06313c00-8c00-11ea-9a92-ca62d0417427.png)

----

- [ ] Remove the extra space between the recommended videos and their descriptions:
![Screenshot_2020-05-01 Youtube(3)](https://user-images.githubusercontent.com/16193212/80852574-06313c00-8c00-11ea-8f1e-d135281cb60d.png)

----

- [ ] [OPTIONAL] Instead of getting images with a background color or taking screenshots of icons use actual icons(<i>). You can find them in sites like [fontaweome](fontawesome.com/), they are easier to style, you style icons like text, and they have a transparent background.
In case you don't want to use icons you can also search for png images with transparent background on google images or svg images.

[Read this article if you are not sure which type of image you should use for each case in web development.](https://www.pagecloud.com/blog/web-images-png-vs-jpg-vs-gif-vs-svg)

[Read this article if you want to know more about SVG images, they are great for logos!](https://css-tricks.com/using-svg/)

----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-04 08:07 UTC, lekegitrepo commented
#### Hi Team, :clap: :clap:
#### The pull request that you submitted has been merged already so I'm marking it as invalid.
#### Note: Reopen the pull request and submit again for a proper review of the required changes from the previous review.

**_if you have any doubts or questions contact me on slack._**

### _Temitayo Adeleke._

2020-05-04 18:32 UTC, lekegitrepo commented
#### Hi Team,
#### I guess you were unable to figure out a better way to fix this.
#### With the current situation of the pull request it can not be reviewed. So, ensure that this problem is fixed before submitting it for review.

### Temitayo Adeleke.

2020-05-05 14:40 UTC, rida-elbahtouri commented
coment